services:
  - type: web
    name: bot-delivery
    runtime: node
    region: oregon
    plan: free
    buildCommand: bash render-build.sh
    startCommand: node dist/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: ENABLE_AI
        value: false
      - key: RESTAURANT_NAME
        value: Meu Delivery
      - key: RESTAURANT_PHONE
        value: 5511999999999
